name: Alerts Cron

on:
  schedule:
    # Hourly (UTC). GitHub Actions uses UTC regardless of repo timezone.
    - cron: "0 * * * *"
  workflow_dispatch:

concurrency:
  group: alerts-cron
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    env:
      BASE: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
      INTERNAL_SYNC_KEY: ${{ secrets.INTERNAL_SYNC_KEY }}
    steps:
      - name: Generate today's alerts (/api/alerts/run)
        run: |
          set -euo pipefail
          curl -sS -f --max-time 20 --retry 3 --retry-delay 5 \
            -H "x-internal-key: $INTERNAL_SYNC_KEY" \
            -X POST "$BASE/api/alerts/run"

      - name: Send alert emails (/api/alerts/email)
        run: |
          set -euo pipefail
          curl -sS -f --max-time 20 --retry 3 --retry-delay 5 \
            -H "x-internal-key: $INTERNAL_SYNC_KEY" \
            -X POST "$BASE/api/alerts/email"
