# .github/workflows/insights-cron.yml
name: Insights cron

on:
  schedule:
    - cron: "10 7 * * *" # daily 07:10 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run clustering
        run: |
          curl -sS -f -X POST \
            -H "x-internal-key: $INTERNAL_SYNC_KEY" \
            "$BASE_URL/api/insights/cluster"
      - name: Summarize + actions
        run: |
          curl -sS -f -X POST \
            -H "x-internal-key: $INTERNAL_SYNC_KEY" \
            "$BASE_URL/api/insights/summarize"
    env:
      BASE_URL: ${{ secrets.RUN_BASE_URL }}         # e.g. https://yourapp.com
      INTERNAL_SYNC_KEY: ${{ secrets.INTERNAL_SYNC_KEY }}
