# .github/workflows/weekly-digest.yml
name: Weekly Digest Cron

on:
  schedule:
    - cron: "0 9 * * 1"   # Mondays at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: weekly-digest-cron
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Call /api/digest/run (with retries)
        env:
          RUN_DIGEST_URL: ${{ secrets.RUN_DIGEST_URL }}          # e.g. https://app.rynith.com/api/digest/run
          INTERNAL_SYNC_KEY: ${{ secrets.INTERNAL_SYNC_KEY }}    # must match server env
        run: |
          set -euo pipefail

          if [ -z "${RUN_DIGEST_URL:-}" ] || [ -z "${INTERNAL_SYNC_KEY:-}" ]; then
            echo "Missing RUN_DIGEST_URL or INTERNAL_SYNC_KEY repo secrets"
            exit 1
          fi

          echo "POST $RUN_DIGEST_URL"
          attempt=0
          max=3
          until [ $attempt -ge $max ]
          do
            attempt=$((attempt+1))
            http_code=$(curl -sS -X POST \
              -H "x-internal-key: $INTERNAL_SYNC_KEY" \
              -o response.json -w "%{http_code}" \
              "$RUN_DIGEST_URL" || true)

            echo "HTTP $http_code"
            cat response.json || true
            echo

            if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 400 ]; then
              echo "Weekly digest OK"
              exit 0
            fi

            echo "Weekly digest failed (try $attempt/$max). Retrying in 10s…"
            sleep 10
          done

          echo "Weekly digest failed after $max attempts"
          exit 1
